knit.dir=./code/example/
test.dir=./code/test/
knit.package=io.github.esafak.kotlintsgen.example
test.package=io.github.esafak.kotlintsgen.example.test
#
test.template=./code/knit-test.ftl
test.language=typescript
knit.include=./code/knit-include.ftl
#test.mode.=\n      .shouldBe
