name: Releases


on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]


concurrency:
  group: "Releases: ${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true


jobs:

  tests:
    uses: ./.github/workflows/run_tests.yml
    permissions:
      checks: write
      contents: read

  publish-maven:
    needs: tests
    # publish snapshots from main and releases from version tags
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/run_publish_maven.yml
    permissions:
      checks: write
      contents: write
      packages: write

  publish-site:
    needs: tests
    # only publish for version tags
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/run_publish_site.yml
    permissions:
      checks: write
      contents: read
      id-token: write   # to verify the deployment originates from an appropriate source
      packages: write
      pages: write      # to deploy to Pages
